### PR TITLE
Update v.50

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@rpaframework-core @xylix
This is ready to review, the linter failure is expected, and the recipe follows directions at
https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-packages-with-os-specific-dependencies
Thank you and regards.

**Comment by rxm7706** [comment]
@rpaframework-core @xylix

Could you please review - all the dependencies have been updated, and I believe this should work. We need this available to move on to the next package as a part of  https://github.com/conda-forge/rpaframework-feedstock/issues/34 

The linter failure is expected, and the recipe follows directions at
https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-packages-with-os-specific-dependencies
Thank you and regards.

**Comment by rxm7706** [comment]
> @rpaframework-core @xylix
> 
> Could you please review - all the dependencies have been updated, and I believe this should work. We need this available to move on to the next package as a part of [conda-forge/rpaframework-feedstock#34](https://github.com/conda-forge/rpaframework-feedstock/issues/34)
> 
> The linter failure is expected, and the recipe follows directions at https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-packages-with-os-specific-dependencies Thank you and regards.

Hi @rpaframework-core @xylix - could you please review and merge - all the other dependencies are complete - https://github.com/conda-forge/rpaframework-feedstock/issues/34 just pending this request and rpaframework-windows to make rpaframework usable again - please let me know if you need assistance with maintainers - I'm happy to raise a request to be added.

**Comment by osrjv** [comment]
Ah, sorry, I don't think @xylix is anymore involved with maintaining these feedstocks. I'll take a look.

Should the `noarch` be removed per linter bot, or is that wanted?

**Comment by rxm7706** [comment]
It

> Ah, sorry, I don't think @xylix is anymore involved with maintaining these feedstocks. I'll take a look.
> 
> Should the `noarch` be removed per linter bot, or is that wanted?

Its needed - and the right way - there is a bug for the linter.

**Pull request merged**
